version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:8000
