version: "3.9"

services:
  db:
    image: postgres:15
    container_name: backend-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phone_dashboard
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s

  api:
    build:
      context: ./backend
    container_name: backend-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phone_dashboard
      POSTGRES_HOST: db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  web:
    build:
      context: ./frontend
    container_name: frontend-web
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

volumes:
  postgres_data:
